In [1]:
import pandas as pd
import numpy as np

In [2]:
path='./data/breast_cancer/breast-cancer-wisconsin.data'
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path, names=column_name)
data.head()

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

In [3]:
# 2、缺失值处理
# 1）替换-》np.nan
data = data.replace(to_replace="?", value=np.nan)
# 2）删除缺失样本
data.dropna(inplace=True)

In [4]:
data.isnull().any() # 不存在缺失值

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [5]:
# 3、划分数据集
from sklearn.model_selection import train_test_split

In [6]:
data.head()

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

In [7]:
x= data.iloc[:,1:-1]

In [8]:
y=data["Class"]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [10]:
x_train.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses
310,2,1,1,1,3,1,2,1,1
435,10,8,10,1,3,10,5,1,1
366,6,10,10,10,8,10,7,10,7
639,5,1,1,3,2,1,1,1,1
85,5,10,6,1,10,4,4,10,10

In [11]:
# 4、标准化
from sklearn.preprocessing import StandardScaler

In [12]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [13]:
x_train

array([[-0.87575493, -0.70173232, -0.74639451, ..., -0.5611001 ,
        -0.61794845, -0.34554141],
       [ 1.95765122,  1.55590559,  2.28657364, ...,  0.68434752,
        -0.61794845, -0.34554141],
       [ 0.54094815,  2.20094499,  2.28657364, ...,  1.51464593,
         2.28767038,  3.19280263],
       ...,
       [ 0.18677238, -0.05669292, -0.07240158, ...,  0.26919831,
         0.35059116, -0.34554141],
       [ 1.95765122,  1.23338589,  1.27558426, ...,  0.68434752,
         1.31913077,  0.2441826 ],
       [ 0.54094815,  2.20094499, -0.40939804, ...,  1.51464593,
         1.64197731,  4.96197466]])

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
# 5、预估器流程
estimator = LogisticRegression()
estimator.fit(x_train, y_train)

LogisticRegression()

In [16]:
# 逻辑回归的模型参数：回归系数和偏置
estimator.coef_

array([[ 1.67033864,  0.11329918,  0.62762164,  0.66563072, -0.02143427,
         1.48832237,  1.21112051,  1.05358877,  1.0714295 ]])

In [17]:
estimator.intercept_

array([-1.10787461])

In [18]:
# 6、模型评估
# 方法1：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值:\n", y_test == y_predict)

# 方法2：计算准确率
score = estimator.score(x_test, y_test)
print("准确率为：\n", score)

y_predict:
 [4 2 2 4 2 2 2 2 4 4 2 4 2 2 4 4 4 4 2 2 2 2 4 4 2 4 2 2 2 2 2 2 4 2 2 2 4
 2 2 2 2 2 2 4 2 2 2 4 4 4 2 2 4 2 4 4 4 2 4 2 4 4 2 4 2 2 2 4 2 2 2 4 4 2
 4 4 2 2 2 2 2 2 2 2 2 2 4 2 4 2 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2
 2 2 2 2 2 4 2 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 2 4 4 4 4 2 4 2 2 2 4 2
 2 4 2 2 2 2 2 2 4 4 4 2 2 4 2 2 4 4 2 4 2 2 4]
直接比对真实值和预测值:
 65     True
102    True
518    True
289    True
388    True
       ...
271    True
190    True
378    True
537    True
604    True
Name: Class, Length: 171, dtype: bool
准确率为：
 0.9590643274853801

In [19]:
# 查看精确率、召回率、F1-score
from sklearn.metrics import classification_report

In [20]:
report = classification_report(y_test, y_predict, labels=[2, 4], target_names=["良性", "恶性"])

In [21]:
print(report)

              precision    recall  f1-score   support

          良性       0.96      0.97      0.97       111
          恶性       0.95      0.93      0.94        60

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.95       171
weighted avg       0.96      0.96      0.96       171

In [22]:
# y_true：每个样本的真实类别，必须为0(反例),1(正例)标记
# 将y_test 转换成 0 1
y_true = np.where(y_test > 3, 1, 0)

In [23]:
y_true

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1])

In [24]:
from sklearn.metrics import roc_auc_score

In [25]:
roc_auc_score(y_true, y_predict)

0.9531531531531532